<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <xacro:include filename="example_include.xacro" /> 

    <!-- first link cqlled "world"-->
    <link name="world"></link>

    <joint name="base_joint" type="fixed">
        <parent link="world" />
        <child link="base_link" />
        <origin xyz="1 1 0" rpy="0.0 0.0 0.0" />
    </joint>
    
    <link name="base_link">
    *** comment ***
        <!-- | <inertial>
        |    <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0" />
        |    <mass value="12" />
        |    <inertia ixx="2.29" ixy="0.0" ixz="0.0" iyy="6.29" iyz="0.0" izz="8.5" />
        |    *** For inertia calculations = "https://www.youtube.com/watch?v=Ga_gOv85fbk" ***
        |</inertial>  -->
        <xacro:inertial_box mass="12" x="2.5" y="1.5" z="0.1">
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0" />
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="2.5 1.5 0.1" />
                *** comment ***
                | <mesh filename="file_path" scale="1.0"/> 
            </geometry>
            <material name="green" />
        </visual>
        <collision> *** collision is exactly as the visual but without the "material" ***
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="2.5 1.5 0.1" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="slider_joint" type="prismatic">
        <parent link="base_link" />
        <child link="slider_link" />
        <axis xyz="1 0 0" />
        <limit lower="0" upper="2" velocity="100" effort="100.0" />
        <origin xyz="-1.25 0 0.1" rpy="0 0 0" />
    </joint>

    <link name="slider_link">
        <xacro:inertial_box mass="0.5" x="0.5" y="0.25" z="0.15">
            <origin xyz="0.0 0.0 0.075" rpy="0.0 0.0 0.0" />
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.075" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.075" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="slider_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="arm_joint" type="revolute">
        <parent link="slider_link" />
        <child link="arm_link" />
        <axis xyz="0 -1 0" />
        <limit lower="0" upper="${pi/2}" velocity="100.0" effort="100.0" />
        <origin xyz="0.25 0 0.15" rpy="0 0 0" />
    </joint>

    <xacro:property name="arm_length" value="1" />
    <xacro:property name="arm_radius" value="0.1" />
    <link name="arm_link">
        <!-- <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.0" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial> -->
        <xacro:inertial_cylinder mass="0.5" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0.0 0.075" rpy="0.0 ${pi/2} 0.0" />
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="${arm_length/2} 0.0 0.075" rpy="0.0 ${pi/2} 0.0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0.0 0.075" rpy="0.0 ${pi/2} 0.0" />
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="arm_link">
        <material>Gazebo/Orange</material>
    </gazebo>


</robot>